---
title: "Intro to R and R Markdown"
author: "Billy Johnson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup
```{r}
source("Setup.R")
```

# Penguins Data
## Load in the data
```{r}
data("penguins")
```

## Explore the data
```{r}
class(penguins)
str(penguins)


class(penguins$species)
str(penguins$species)
```

## Create a list
```{r}
myList <- list("apple", 1993, FALSE, penguins)
```

```{r}
list(myList, list("more stuff here", list("and more")))
```

```{r}
names(myList) <- c("fruit", "year", "logic", "data")

names(myList)
```

# Indexing
Index lists
```{r}
myList[[1]]

myList[["data"]]
```


Index vectors
```{r}
# For vectors we can use single brackets
myVector <- c("apple", "banana", "pear")

myVector[2]
```

Indexing Dataframes
```{r}
# Dataframe [rows, columns]
penguins[1:5, 2]

penguins[1:5, "island"]

penguins[1, 1:5]

penguins[1:5, c("species","sex")]

penguins[penguins$sex=='female',]

# $ for a single column
penguins$species
```


# The dplr package

subset rows with filter
```{r}
filter(penguins, species == "Adelie")

filter(penguins, species != "Adelie")

filter(penguins, island %in% c("Dream", "Torgersen") & !is.na(bill_length_mm))
```


Select columns with select()
```{r}
# Select two specific variables
select(penguins, species, sex)

# Select a range of variables
select(penguins, species:flipper_length_mm)

# Rename columns within select
select(penguins, genus = species, island)

# Select column variables that are recorded in mm
select(penguins, contains("mm"))
```

Create new variables with mutate
```{r}
# New variable that calculates bill length in cm
mutate(penguins, bill_length_cm = bill_length_mm/10)

# mutate based on conditional statements
mutate(penguins, species_sex = if_else(sex == 'male', paste0(species,"_m"), paste0(species, "_f")))
```

### the pipe
start with this 
```{r}
df1 <- filter(penguins, island == "Dream")
df2 <- mutate(df1, flipper_length_cm = flipper_length_mm/10)
df3 <- select(df2, species, year, flipper_length_cm)

print(df3)
```

Turn it to this with the pipe
```{r}
penguins %>% 
  filter(island == "Dream") %>% 
  mutate(flipper_length_cm = flipper_length_mm/10) %>% 
  select(species, year, flipper_length_cm)
```

# Visualize

ggplot(data = <DATA>) + 
  <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))

```{r}
ggplot(penguins) + 
  geom_histogram(mapping = aes(x = flipper_length_mm))
```

```{r}
# Histogram example: flipper length by species
ggplot(penguins) +
  geom_histogram(aes(x = flipper_length_mm, fill = species), alpha = 0.5, position = "identity") +
  scale_fill_manual(values = c("darkorange","darkorchid","cyan4"))
```

```{r}
ggplot(penguins) +
  geom_histogram(aes(x = flipper_length_mm, fill = species), alpha = 0.5, position = "identity") +
  scale_fill_manual(values = c("darkorange","darkorchid","cyan4")) +
  facet_wrap(~species)
```

```{r}
ggplot(penguins) +
  geom_bar(mapping = aes(x = island, fill = species))
```

```{r}
ggplot(penguins, aes(x = island, fill = species)) +
  geom_bar(alpha = 0.8) +
  scale_fill_manual(values = c("darkorange","purple","cyan4"), 
                    guide = FALSE) +
  theme_minimal() +
  facet_wrap(~species, ncol = 1) +
  coord_flip()
```

```{r}
ggplot(penguins) +
  geom_point(mapping = aes(x = body_mass_g, y = flipper_length_mm, color = species))
```

```{r}
# Add some more code
```

